{
  "ErsatzTVFillerTheme": {
    "ThemeName": "StopandGo",
    "Creator": "liam8888999",
    "ThemeVersion": "2"
  },
  "Offline": {
  "offlinetextcolour": "ff6666",
  "offlinetitlecolour": "ff0000",
  "offlinebackgroundcolour": "90ee90"
  },
  "News": {
  "newstextcolour": "ff6666",
  "newstitlecolour": "ff0000",
  "newsbackgroundcolour": "90ee90"
  },
  "Weather": {
  "weatherbackgroundcolour": "90ee90"
  }
}
