{
  "ErsatzTVFillerTheme": {
    "ThemeName": "MoRBiD_MaNGLeR_Dark",
    "Creator": "MoRBiD_MaNGLeR",
    "ThemeVersion": "2"
  },
  "Offline": {
  "offlinetextcolour": "ffff66",
  "offlinetitlecolour": "ffff00",
  "offlinebackgroundcolour": "000000"
  },
  "News": {
  "newstextcolour": "ffff66",
  "newstitlecolour": "ffff00",
  "newsbackgroundcolour": "000000"
  },
  "Weather": {
  "weatherbackgroundcolour": "000000"
  }
}
