{
  "ErsatzTVFillerTheme": {
    "ThemeName": "SystemDark",
    "Creator": "liam8888999",
    "ThemeVersion": "2"
  },
  "Offline": {
  "offlinetextcolour": "c0c0c0",
  "offlinetitlecolour": "ffffff",
  "offlinebackgroundcolour": "000000"
  },
  "News": {
  "newstextcolour": "c0c0c0",
  "newstitlecolour": "ffffff",
  "newsbackgroundcolour": "000000"
  },
  "Weather": {
  "weatherbackgroundcolour": "000000"
  }
}
